# Site settings
theme: jekyll-theme-slate
title: Eh, this site could be worse.
description: >
  Viktor's unexplained website.
permalink: pretty
url: https://www.viktorroytman.com
repository: vr2262/viktor-roytman.gitlab.io

# Build settings
markdown: kramdown
